# Generated by Django 4.1 on 2023-08-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('respuestas_predefinidas', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['semestre', 'clave_asignatura']},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.formulario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='respuestas',
            field=models.ManyToManyField(through='inscripcion.RespuestaFormulario', to='inscripcion.pregunta'),
        ),
    ]
