# Generated by Django 4.1 on 2023-08-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaformulario',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='respuestaformulario',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='RespuestaFormulario',
        ),
    ]
