# Generated by Django 4.1 on 2023-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_formulario_pregunta_respuestaformulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
