# Generated by Django 4.1 on 2023-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_formulario_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='completado',
        ),
        migrations.AddField(
            model_name='formulario',
            name='formulario_activo',
            field=models.BooleanField(default=True),
        ),
    ]
