# Generated by Django 4.1 on 2023-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0014_alter_pregunta_respuestas_predefinidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden']},
        ),
    ]
